"""Initial V3 tables

Revision ID: 512cf5c965a8
Revises: 
Create Date: 2026-01-31 19:34:39.845637

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '512cf5c965a8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('clickup_task_id', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('has_implementation', sa.Boolean(), nullable=True),
    sa.Column('has_integration', sa.Boolean(), nullable=True),
    sa.Column('has_support', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_projects_clickup_task_id'), ['clickup_task_id'], unique=True)

    op.create_table('integration_logic',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('clickup_task_id', sa.String(length=50), nullable=False),
    sa.Column('clickup_status', sa.String(length=100), nullable=True),
    sa.Column('clickup_url', sa.String(length=255), nullable=True),
    sa.Column('assignee_name', sa.String(length=100), nullable=True),
    sa.Column('assignee_id', sa.String(length=50), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('finish_date', sa.DateTime(), nullable=True),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.Column('days_in_status', sa.Integer(), nullable=True),
    sa.Column('total_duration_days', sa.Integer(), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('integration_logic')
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_projects_clickup_task_id'))

    op.drop_table('projects')
    # ### end Alembic commands ###
