"""Initial schema

Revision ID: 7f1b7432f755
Revises: 
Create Date: 2025-12-28 21:36:22.723547

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f1b7432f755'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('metrics_snapshot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reference_date', sa.DateTime(), nullable=True),
    sa.Column('implantador', sa.String(length=100), nullable=True),
    sa.Column('total_lojas', sa.Integer(), nullable=True),
    sa.Column('tempo_medio_loja', sa.Float(), nullable=True),
    sa.Column('tempo_medio_etapa', sa.Float(), nullable=True),
    sa.Column('retrabalho_total', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_name', sa.String(length=255), nullable=False),
    sa.Column('custom_store_id', sa.String(length=50), nullable=True),
    sa.Column('clickup_task_id', sa.String(length=50), nullable=False),
    sa.Column('clickup_url', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('implantador', sa.String(length=100), nullable=True),
    sa.Column('valor_mensalidade', sa.String(length=50), nullable=True),
    sa.Column('valor_implantacao', sa.String(length=50), nullable=True),
    sa.Column('erp', sa.String(length=100), nullable=True),
    sa.Column('cnpj', sa.String(length=50), nullable=True),
    sa.Column('crm', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('total_time_days', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('clickup_task_id'),
    sa.UniqueConstraint('custom_store_id')
    )
    op.create_table('task_status_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clickup_task_id', sa.String(length=50), nullable=False),
    sa.Column('old_status', sa.String(length=50), nullable=True),
    sa.Column('new_status', sa.String(length=50), nullable=True),
    sa.Column('changed_at', sa.DateTime(), nullable=False),
    sa.Column('user', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tasks_steps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clickup_task_id', sa.String(length=50), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('step_list_id', sa.String(length=50), nullable=True),
    sa.Column('step_name', sa.String(length=100), nullable=True),
    sa.Column('assignee', sa.String(length=100), nullable=True),
    sa.Column('start_real_at', sa.DateTime(), nullable=True),
    sa.Column('end_real_at', sa.DateTime(), nullable=True),
    sa.Column('total_time_days', sa.Float(), nullable=True),
    sa.Column('reopen_count', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('clickup_task_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tasks_steps')
    op.drop_table('task_status_history')
    op.drop_table('stores')
    op.drop_table('metrics_snapshot')
    # ### end Alembic commands ###
