"""Add_Legacy_Fields_V3.1

Revision ID: a31bb9bbcff2
Revises: d5e8cd4ce1cc
Create Date: 2026-01-31 21:44:04.584067

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a31bb9bbcff2'
down_revision = 'd5e8cd4ce1cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_pauses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('task_steps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('clickup_task_id', sa.String(length=50), nullable=True),
    sa.Column('step_name', sa.String(length=255), nullable=True),
    sa.Column('step_group', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('assignee', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('idle_days', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('clickup_task_id')
    )
    with op.batch_alter_table('implementation_logic', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deployment_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('state_uf', sa.String(length=2), nullable=True))
        batch_op.add_column(sa.Column('manual_go_live_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('projected_orders', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('had_ecommerce', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('previous_platform', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('ai_summary', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('ai_analyzed_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('implementation_logic', schema=None) as batch_op:
        batch_op.drop_column('ai_analyzed_at')
        batch_op.drop_column('ai_summary')
        batch_op.drop_column('previous_platform')
        batch_op.drop_column('had_ecommerce')
        batch_op.drop_column('projected_orders')
        batch_op.drop_column('manual_go_live_date')
        batch_op.drop_column('state_uf')
        batch_op.drop_column('deployment_type')

    op.drop_table('task_steps')
    op.drop_table('project_pauses')
    # ### end Alembic commands ###
