"""Added manual fields

Revision ID: aadbcf8fec6a
Revises: 7f1b7432f755
Create Date: 2025-12-28 21:56:04.798031

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aadbcf8fec6a'
down_revision = '7f1b7432f755'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('observacoes', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('tempo_contrato', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('status_pagamento', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('manual_finished_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('considerar_tempo_implantacao', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('justificativa_tempo_implantacao', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('teve_retrabalho', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stores', schema=None) as batch_op:
        batch_op.drop_column('teve_retrabalho')
        batch_op.drop_column('justificativa_tempo_implantacao')
        batch_op.drop_column('considerar_tempo_implantacao')
        batch_op.drop_column('manual_finished_at')
        batch_op.drop_column('status_pagamento')
        batch_op.drop_column('tempo_contrato')
        batch_op.drop_column('observacoes')

    # ### end Alembic commands ###
