"""add implementation logic

Revision ID: d5e8cd4ce1cc
Revises: 512cf5c965a8
Create Date: 2026-01-31 19:54:50.645621

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5e8cd4ce1cc'
down_revision = '512cf5c965a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('implementation_logic',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('status_norm', sa.String(length=50), nullable=True),
    sa.Column('manual_finished_at', sa.DateTime(), nullable=True),
    sa.Column('valor_mensalidade', sa.Float(), nullable=True),
    sa.Column('valor_implantacao', sa.Float(), nullable=True),
    sa.Column('tempo_contrato', sa.Integer(), nullable=True),
    sa.Column('implantador_id', sa.String(length=50), nullable=True),
    sa.Column('implantador_name', sa.String(length=100), nullable=True),
    sa.Column('tipo_loja', sa.String(length=50), nullable=True),
    sa.Column('rede', sa.String(length=100), nullable=True),
    sa.Column('erp', sa.String(length=100), nullable=True),
    sa.Column('start_real_at', sa.DateTime(), nullable=True),
    sa.Column('end_real_at', sa.DateTime(), nullable=True),
    sa.Column('last_interaction_at', sa.DateTime(), nullable=True),
    sa.Column('idle_days', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('project_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('implementation_logic')
    # ### end Alembic commands ###
