"""v3_0_production_ready

Revision ID: e611f09d7731
Revises: 
Create Date: 2026-03-16 16:38:09.312059

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e611f09d7731'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('metrics_snapshot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reference_date', sa.DateTime(), nullable=True),
    sa.Column('total_lojas_em_progresso', sa.Integer(), nullable=True),
    sa.Column('total_lojas_concluidas', sa.Integer(), nullable=True),
    sa.Column('mrr_em_implantacao', sa.Float(), nullable=True),
    sa.Column('pct_no_prazo', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('module', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('status_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clickup_task_id', sa.String(length=50), nullable=False),
    sa.Column('old_status', sa.String(length=50), nullable=True),
    sa.Column('new_status', sa.String(length=50), nullable=True),
    sa.Column('changed_at', sa.DateTime(), nullable=False),
    sa.Column('changed_by', sa.String(length=100), nullable=True),
    sa.Column('entity_type', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('status_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_status_events_clickup_task_id'), ['clickup_task_id'], unique=False)

    op.create_table('stores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_name', sa.String(length=255), nullable=False),
    sa.Column('custom_store_id', sa.String(length=50), nullable=True),
    sa.Column('clickup_task_id', sa.String(length=50), nullable=False),
    sa.Column('clickup_url', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('status_raw', sa.String(length=50), nullable=True),
    sa.Column('status_norm', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('start_real_at', sa.DateTime(), nullable=True),
    sa.Column('end_real_at', sa.DateTime(), nullable=True),
    sa.Column('total_time_days', sa.Float(), nullable=True),
    sa.Column('idle_days', sa.Integer(), nullable=True),
    sa.Column('implantador', sa.String(length=100), nullable=True),
    sa.Column('implantador_original', sa.String(length=100), nullable=True),
    sa.Column('implantador_atual', sa.String(length=100), nullable=True),
    sa.Column('integrador', sa.String(length=100), nullable=True),
    sa.Column('valor_mensalidade', sa.Float(), nullable=True),
    sa.Column('valor_implantacao', sa.Float(), nullable=True),
    sa.Column('financeiro_status', sa.String(length=50), nullable=True),
    sa.Column('erp', sa.String(length=100), nullable=True),
    sa.Column('cnpj', sa.String(length=50), nullable=True),
    sa.Column('crm', sa.String(length=50), nullable=True),
    sa.Column('rede', sa.String(length=100), nullable=True),
    sa.Column('tipo_loja', sa.String(length=50), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('tempo_contrato', sa.Integer(), nullable=True),
    sa.Column('manual_finished_at', sa.DateTime(), nullable=True),
    sa.Column('considerar_tempo_implantacao', sa.Boolean(), nullable=True),
    sa.Column('justificativa_tempo_implantacao', sa.String(length=255), nullable=True),
    sa.Column('teve_retrabalho', sa.Boolean(), nullable=True),
    sa.Column('retrabalho_tipo', sa.String(length=100), nullable=True),
    sa.Column('delivered_with_quality', sa.Boolean(), nullable=True),
    sa.Column('is_manual_start_date', sa.Boolean(), nullable=True),
    sa.Column('ai_summary', sa.Text(), nullable=True),
    sa.Column('ai_analyzed_at', sa.DateTime(), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('state_uf', sa.String(length=2), nullable=True),
    sa.Column('had_ecommerce', sa.Boolean(), nullable=True),
    sa.Column('previous_platform', sa.String(length=100), nullable=True),
    sa.Column('deployment_type', sa.String(length=50), nullable=True),
    sa.Column('projected_orders', sa.Integer(), nullable=True),
    sa.Column('order_rate', sa.Float(), nullable=True),
    sa.Column('manual_go_live_date', sa.DateTime(), nullable=True),
    sa.Column('forecast_obs', sa.Text(), nullable=True),
    sa.Column('include_in_forecast', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('clickup_task_id'),
    sa.UniqueConstraint('custom_store_id')
    )
    op.create_table('sync_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('items_processed', sa.Integer(), nullable=True),
    sa.Column('items_updated', sa.Integer(), nullable=True),
    sa.Column('error_summary', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sync_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('last_shallow_sync_at', sa.DateTime(), nullable=True),
    sa.Column('last_successful_sync_at', sa.DateTime(), nullable=True),
    sa.Column('in_progress', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('system_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=50), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('profile_picture', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('totp_secret', sa.String(length=32), nullable=True),
    sa.Column('totp_enabled', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=True),
    sa.Column('resource_id', sa.String(length=50), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('forecast_audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('field_name', sa.String(length=50), nullable=False),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('changed_at', sa.DateTime(), nullable=True),
    sa.Column('actor', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('integration_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('sla_days', sa.Integer(), nullable=True),
    sa.Column('post_go_live_bugs', sa.Integer(), nullable=True),
    sa.Column('churn_risk', sa.Boolean(), nullable=True),
    sa.Column('documentation_status', sa.String(length=20), nullable=True),
    sa.Column('points', sa.Float(), nullable=True),
    sa.Column('lead_time_days', sa.Integer(), nullable=True),
    sa.Column('ticket_count', sa.Integer(), nullable=True),
    sa.Column('has_blocking_issue', sa.Boolean(), nullable=True),
    sa.Column('last_blocker_reason', sa.String(length=255), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('metrics_snapshot_daily',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('implantador', sa.String(length=100), nullable=True),
    sa.Column('rede', sa.String(length=100), nullable=True),
    sa.Column('status_norm', sa.String(length=50), nullable=True),
    sa.Column('days_in_stage', sa.Integer(), nullable=True),
    sa.Column('idle_days', sa.Integer(), nullable=True),
    sa.Column('wip_points', sa.Float(), nullable=True),
    sa.Column('mrr', sa.Float(), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('ai_risk_level', sa.String(length=20), nullable=True),
    sa.Column('ai_summary', sa.Text(), nullable=True),
    sa.Column('ai_network_summary', sa.Text(), nullable=True),
    sa.Column('ai_action_plan', sa.Text(), nullable=True),
    sa.Column('ai_last_analysis', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('snapshot_date', 'store_id', name='uix_snapshot_date_store')
    )
    with op.batch_alter_table('metrics_snapshot_daily', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_metrics_snapshot_daily_implantador'), ['implantador'], unique=False)
        batch_op.create_index(batch_op.f('ix_metrics_snapshot_daily_snapshot_date'), ['snapshot_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_metrics_snapshot_daily_store_id'), ['store_id'], unique=False)

    op.create_table('performance_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('cycle', sa.String(length=20), nullable=False),
    sa.Column('soft_communication', sa.Float(), nullable=True),
    sa.Column('soft_process', sa.Float(), nullable=True),
    sa.Column('soft_responsibility', sa.Float(), nullable=True),
    sa.Column('score_collective', sa.Float(), nullable=True),
    sa.Column('score_individual', sa.Float(), nullable=True),
    sa.Column('churn_count', sa.Integer(), nullable=True),
    sa.Column('final_score', sa.Float(), nullable=True),
    sa.Column('bonus_eligible', sa.Boolean(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('reviewer_comment', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'cycle', name='uix_user_cycle_review')
    )
    op.create_table('role_permissions',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('role_id', 'permission_id')
    )
    op.create_table('store_deep_sync_state',
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('last_deep_sync_at', sa.DateTime(), nullable=True),
    sa.Column('sync_status', sa.String(length=20), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('last_synced_clickup_updated_at', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('store_id')
    )
    op.create_table('store_pauses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('store_sync_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('field_name', sa.String(length=50), nullable=False),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('changed_at', sa.DateTime(), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sync_errors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sync_run_id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=True),
    sa.Column('task_id', sa.String(length=50), nullable=True),
    sa.Column('error_msg', sa.Text(), nullable=True),
    sa.Column('traceback', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['sync_run_id'], ['sync_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tasks_steps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clickup_task_id', sa.String(length=50), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('step_list_name', sa.String(length=100), nullable=True),
    sa.Column('step_name', sa.String(length=150), nullable=True),
    sa.Column('assignee', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('start_real_at', sa.DateTime(), nullable=True),
    sa.Column('end_real_at', sa.DateTime(), nullable=True),
    sa.Column('total_time_days', sa.Float(), nullable=True),
    sa.Column('idle_days', sa.Integer(), nullable=True),
    sa.Column('reopen_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('clickup_task_id')
    )
    op.create_table('time_in_status_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('status_name', sa.String(length=50), nullable=False),
    sa.Column('total_seconds', sa.Integer(), nullable=True),
    sa.Column('total_days', sa.Float(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_roles',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_roles')
    op.drop_table('time_in_status_cache')
    op.drop_table('tasks_steps')
    op.drop_table('sync_errors')
    op.drop_table('store_sync_logs')
    op.drop_table('store_pauses')
    op.drop_table('store_deep_sync_state')
    op.drop_table('role_permissions')
    op.drop_table('performance_reviews')
    with op.batch_alter_table('metrics_snapshot_daily', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_metrics_snapshot_daily_store_id'))
        batch_op.drop_index(batch_op.f('ix_metrics_snapshot_daily_snapshot_date'))
        batch_op.drop_index(batch_op.f('ix_metrics_snapshot_daily_implantador'))

    op.drop_table('metrics_snapshot_daily')
    op.drop_table('integration_metrics')
    op.drop_table('forecast_audit_logs')
    op.drop_table('audit_logs')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    op.drop_table('system_config')
    op.drop_table('sync_state')
    op.drop_table('sync_runs')
    op.drop_table('stores')
    with op.batch_alter_table('status_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_status_events_clickup_task_id'))

    op.drop_table('status_events')
    op.drop_table('roles')
    op.drop_table('permissions')
    op.drop_table('metrics_snapshot')
    # ### end Alembic commands ###
